server:
  port: 8082
  tomcat:
    accept-count: 25
    max-connections: 100
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
hm:
  db:
    database: hm-cart
  swagger:
    title: "黑马商城购物车服务接口文档"
    package: com.hmall.cart.controller
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true #开启请求方式前缀
