server:
  port: 8081
hm:
  db:
    database: hm-item
  swagger:
    title: "黑马商城购物车服务接口文档"
    package: com.hmall.item.controller
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
  sentinel:
    enabled: true # 开启Feign对Sentinel的整合